save_dir: workspace/test_script
model:
  arch:
    name: NanoDetPlus
    detach_epoch: 10
    backbone:
      name: ResNet
      depth: 18
      out_stages: [2,3,4]
      activation: ReLU6
      pretrain: True
    fpn:
      name: GhostPAN
      in_channels: [128, 256,512]
      out_channels: 64
      kernel_size: 5
      num_extra_level: 1
      use_depthwise: False
      activation: ReLU6
    head:
      name: NanoDetPlusHead
      num_classes: 8
      input_channel: 64
      feat_channels: 64
      stacked_convs: 2
      kernel_size: 5
      strides: [8, 16, 32, 64]
      activation: ReLU6
      conv_type: Conv
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
    # Auxiliary head, only use in training time.
    aux_head:
      name: SimpleConvHead
      num_classes: 8
      input_channel: 128
      feat_channels: 128
      stacked_convs: 4
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7

class_names:  &class_names ['person', 'rider', 'non-motor', 'vehicle', 'face','carplate']
data:
  train:
    name: YoloDataset
#    img_path: coco/train2017
#    ann_path: coco/train2017
    img_path: /Users/wangjunjie/work/VisionularDet/dataset/wz_det_v6/train/images
    ann_path: /Users/wangjunjie/work/VisionularDet/dataset/wz_det_v6/train/v6_labels
    class_names: *class_names
    input_size: [320,320] #[w,h]
    keep_ratio: False
    keep_scale: False
    lowpass_cascade: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[0.8, 1.2], [0.8, 1.2]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: YoloDataset
    img_path: /Users/wangjunjie/work/VisionularDet/dataset/wz_det_v6/val/images
    ann_path: /Users/wangjunjie/work/VisionularDet/dataset/wz_det_v6/val/v6_labels
    class_names: *class_names
    input_size: [320,320] #[w,h]
    keep_ratio: False
    keep_scale: False
    lowpass_cascade: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [1]
  workers_per_gpu: 10
  batchsize_per_gpu: 96
schedule:
  # resume: True
  # load_model: /mnt/data/wjj/nanodet/workspace/v3_model_retrain/nanodet-plus-m-NPU128v1_320/model_last.ckpt
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  # total_epochs: 300
  total_epochs: 100
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 300
    eta_min: 0.00005
  val_intervals: 1
grad_clip: 35
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 50
